// Post-build step (runs after `vite build` as part of `npm run build`).
// The app is a client-rendered SPA on static hosting. Hostinger publishes `dist/` into public_html and
// regenerates public_html/.htaccess on each deploy, so the site must not depend on rewrite rules:
// every public route is written as a real folder (`dist/about/index.html` → /about/) carrying that
// route's own title, description, robots, canonical, social and JSON-LD tags. Also generates redirect
// pages for duplicate routes, 404.html, sitemap.xml, robots.txt and an optional .htaccess that adds
// www/HTTPS redirects and the branded 404 page when the host keeps it.
import { access, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { CONTACT } from '../src/data.js'
import en from '../src/i18n/en.js'
import { NOT_FOUND_META, REDIRECTS, ROUTES, SITE_URL, headFor, headTags, jsonLdFor, pagePath, pageUrl } from '../src/seo.js'

const DIST = fileURLToPath(new URL('../dist/', import.meta.url))
const SEO_BLOCK = /<!-- seo:start[\s\S]*?<!-- seo:end -->/
const NOSCRIPT_MARK = '<!-- seo:noscript -->'
const NAV = [['Home', '/'], [en.nav.about, '/about'], [en.nav.services, '/services'], [en.nav.programs, '/programs'], [en.nav.journal, '/articles'], [en.nav.book, '/book-consultation']]

const escapeHtml = (value) => String(value).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
const routeFile = (path) => (path === '/' ? 'index.html' : `${path.slice(1)}/index.html`)

function renderHead(route) {
  const head = headFor(route)
  const tags = headTags(route)
    .filter(([, , value]) => value != null)
    .map(([attr, key, value]) => attr === 'rel'
      ? `<link rel="${key}" href="${escapeHtml(value)}" />`
      : `<meta ${attr}="${key}" content="${escapeHtml(value)}" />`)
  const lines = [`<title>${escapeHtml(head.title)}</title>`, ...tags]
  if (route.hero) lines.push(`<link rel="preload" as="image" href="${escapeHtml(route.hero)}" fetchpriority="high" />`)
  const ld = jsonLdFor(route)
  if (ld) lines.push(`<script type="application/ld+json" id="ld-json">${JSON.stringify(ld).replace(/</g, '\\u003c')}</script>`)
  return lines.join('\n    ')
}

/** Plain fallback for visitors and crawlers without JavaScript; hidden whenever the app runs. */
function renderNoscript(route) {
  const head = headFor(route)
  const links = NAV.map(([label, path]) => `<a href="${pagePath(path)}">${escapeHtml(label)}</a>`).join(' · ')
  return `<noscript><div style="max-width:720px;margin:40px auto;padding:0 16px;font-family:sans-serif;line-height:1.6">`
    + `<p><strong>${escapeHtml(head.title)}</strong></p><p>${escapeHtml(head.description)}</p><p>${links}</p>`
    + `<p><a href="${CONTACT.phoneHref}">${CONTACT.phone}</a> · <a href="${CONTACT.emailHref}">${CONTACT.email}</a></p></div></noscript>`
}

function renderPage(template, route) {
  if (!SEO_BLOCK.test(template) || !template.includes(NOSCRIPT_MARK)) throw new Error('dist/index.html is missing the seo:start/seo:end or seo:noscript markers')
  return template.replace(SEO_BLOCK, renderHead(route)).replace(NOSCRIPT_MARK, renderNoscript(route))
}

/** Instant meta refresh: treated by Google as a permanent redirect when the server-side 301 is unavailable. */
function renderRedirect(to) {
  const target = pagePath(to)
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Redirecting…</title>
    <link rel="canonical" href="${pageUrl(to)}" />
    <meta http-equiv="refresh" content="0; url=${target}" />
    <script>location.replace(${JSON.stringify(target)} + location.search + location.hash)</script>
  </head>
  <body><p><a href="${target}">Continue to ${escapeHtml(pageUrl(to))}</a></p></body>
</html>
`
}

function renderSitemap() {
  const urls = ROUTES.filter((r) => !r.noindex).map((r) => `  <url><loc>${pageUrl(r.path)}</loc></url>`)
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>\n`
}

const renderRobots = () => `User-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap.xml\n`

function renderHtaccess() {
  const host = new URL(SITE_URL).host
  const redirects = Object.entries(REDIRECTS).map(([from, to]) => `RewriteRule ^${from.slice(1)}/?$ ${pageUrl(to)} [R=301,L]`)
  return `# Generated by scripts/prerender.mjs. Optional: every page is a real folder, so the site also works
# if the host replaces this file. When kept, it adds single-hop 301s and the branded 404 page.
Options -MultiViews -Indexes
DirectoryIndex index.html
ErrorDocument 404 /404.html

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /

# www -> https://${host}
RewriteCond %{HTTP_HOST} ^www\\.${host.replace(/\./g, '\\.')}$ [NC]
RewriteRule ^(.*)$ ${SITE_URL}/$1 [R=301,L]

# Force HTTPS (the X-Forwarded-Proto check prevents loops behind a TLS-terminating proxy/CDN)
RewriteCond %{HTTPS} off
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule ^(.*)$ ${SITE_URL}/$1 [R=301,L]

# .../index.html -> folder URL
RewriteCond %{THE_REQUEST} \\s/(.*/)?index\\.html[\\s?]
RewriteRule ^(.*/)?index\\.html$ ${SITE_URL}/$1 [R=301,L]

# Duplicate routes -> preferred URL
${redirects.join('\n')}

# Page folders without the trailing slash -> canonical URL, in one HTTPS hop
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^(.*[^/])$ ${SITE_URL}/$1/ [R=301,L]
</IfModule>
`
}

async function write(file, content) {
  const target = join(DIST, file)
  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, content)
}

const template = await readFile(join(DIST, 'index.html'), 'utf8')
for (const route of ROUTES) await write(routeFile(route.path), renderPage(template, route))
for (const [from, to] of Object.entries(REDIRECTS)) await write(routeFile(from), renderRedirect(to))
await write('404.html', renderPage(template, NOT_FOUND_META))
await write('sitemap.xml', renderSitemap())
await write('robots.txt', renderRobots())
await write('.htaccess', renderHtaccess())

// Fail the build (and therefore the deploy) if any expected output is missing.
const expected = [...ROUTES.map((r) => routeFile(r.path)), ...Object.keys(REDIRECTS).map(routeFile), '404.html', 'sitemap.xml', 'robots.txt', '.htaccess']
await Promise.all(expected.map((file) => access(join(DIST, file))))
console.log(`prerender: ${ROUTES.length} pages, ${Object.keys(REDIRECTS).length} redirects, 404.html, sitemap.xml (${ROUTES.filter((r) => !r.noindex).length} URLs), robots.txt, .htaccess`)
