import { useEffect, useRef, useState } from 'react'
import { Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { articles, programs, services } from './content'

const Arrow = () => <span className="arrow" aria-hidden="true">→</span>
const Leaf = ({className=''}) => <svg className={`leaf-icon ${className}`} viewBox="0 0 36 36" aria-hidden="true"><path d="M18 30c0-12 4-19 13-25-1 12-4 19-13 25Zm0 0C15 19 10 13 3 9c1 11 6 18 15 21Zm0 0v5"/><path d="M19 27c3-7 7-12 11-16M16 27C13 20 9 16 5 13"/></svg>
const HeroFoliage = () => <svg className="hero-foliage" viewBox="0 0 420 760" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 760C34 570 102 420 188 300S320 92 402 10"/><path d="M79 588c-45-30-67-71-65-121 54 8 80 46 65 121Zm45-112c-38-39-43-82-22-125 48 23 58 67 22 125Zm56-112c-31-42-29-86-3-121 42 28 46 72 3 121Zm58-107c-17-43-4-82 28-110 31 36 24 76-28 110Z"/><path d="M69 598c53-26 97-15 128 17-42 36-85 34-128-17Zm54-117c52-21 94-5 120 31-43 31-85 24-120-31Zm55-112c48-17 84 3 104 36-38 27-74 17-104-36Zm56-106c37-9 67 9 80 34-31 17-57 8-80-34Z"/></g></svg>
const SageArt = () => <svg className="sage-art" viewBox="0 0 320 390" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M176 30c17-22 45-20 58 1 6 11 5 25-2 37m-68-34c3-20 18-33 38-33 17 0 31 9 37 24"/><path d="M153 76c-4-31 17-54 47-54 31 0 50 22 47 52-1 24-14 53-36 65-12 7-26 6-40-3-17-12-25-37-18-60Z"/><path d="M156 77c13-8 30-11 46-7m-36 22c11 8 25 10 40 4m-40 16c4 18 16 28 32 28 15 0 26-9 31-25m-39-13 9 4 6-4m-45-15c9 7 18 6 27 1m20-2c9 4 17 3 25-2"/><path d="M169 142c-17 7-39 19-53 43l-43 102m104-145c11 7 26 7 39 0 32 10 52 28 63 57l31 88M115 184c29 26 68 38 109 34M104 233c35 14 78 19 132 6M88 286c56-22 116-22 179 4M61 329c67-25 139-25 214 3"/><path d="M128 174c4 41 7 78 3 111m99-113c-3 39-1 78 8 115M147 169c8 22 22 37 42 45m-43-3c-14 22-20 44-22 67m85-68c15 24 22 47 22 72"/><path d="M192 38c-8 8-11 17-10 29m28-25c10 10 13 20 11 31m-71 178c14 9 29 13 46 12"/></g></svg>

function Button({to, children, tone='gold', className=''}) { return <Link className={`btn btn-${tone} ${className}`} to={to}>{children}<Arrow /></Link> }

function Reveal({children,className='',delay=0}) {
  const ref=useRef(null)
  useEffect(()=>{ const el=ref.current; if(!el)return; const io=new IntersectionObserver(([e])=>{if(e.isIntersecting){el.classList.add('is-visible');io.disconnect()}},{threshold:.12}); io.observe(el); return()=>io.disconnect()},[])
  return <div ref={ref} className={`reveal ${className}`} style={{'--delay':`${delay}ms`}}>{children}</div>
}

function Logo({footer=false}) { return <Link to="/" className={`brand ${footer?'brand-footer':''}`} aria-label="AyurvedaVaidya home"><img src="/images/ayurveda/ayurvedavaidya-logo-transparent.webp" alt="AyurvedaVaidya.com — Ancient Wisdom. Modern Wellbeing." /></Link> }
const NavChevron = () => <svg className="nav-chevron" viewBox="0 0 12 8" aria-hidden="true"><path d="m1 1 5 5 5-5"/></svg>

function Header(){
 const [open,setOpen]=useState(false),[servicesOpen,setServicesOpen]=useState(false); const loc=useLocation(); const menuButtonRef=useRef(null),drawerRef=useRef(null);
 useEffect(()=>{setOpen(false);setServicesOpen(false)},[loc.pathname]);
 useEffect(()=>{document.body.classList.toggle('nav-open',open);if(open)drawerRef.current?.querySelector('.drawer-close')?.focus();const keys=e=>{if(e.key==='Escape'){setOpen(false);menuButtonRef.current?.focus()}if(e.key==='Tab'&&open&&drawerRef.current){const els=[...drawerRef.current.querySelectorAll('a,button:not([disabled])')];if(!els.length)return;const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};addEventListener('keydown',keys);return()=>{removeEventListener('keydown',keys);document.body.classList.remove('nav-open')}},[open]);
 return <header className="site-header"><div className="nav-shell"><Logo/><nav className="desktop-nav" aria-label="Primary navigation">
  <NavLink to="/">Home</NavLink><NavLink to="/about">About</NavLink>
  <div className="menu-wrap" onMouseEnter={()=>setServicesOpen(true)} onMouseLeave={()=>setServicesOpen(false)}>
   <button className="nav-drop" aria-expanded={servicesOpen} onClick={()=>setServicesOpen(v=>!v)}>Ayurveda <NavChevron/></button>
   <div className={`mega-menu ${servicesOpen?'open':''}`}><div className="mega-intro"><Leaf/><span>AYURVEDA 360°</span><strong>Four dimensions.<br/>One personal plan.</strong><Link to="/services">Explore all services <Arrow/></Link></div>{services.map(s=><div key={s.key} className="mega-col"><Link className="mega-title" to={`/services/${s.key}`}>{s.title}</Link>{s.items.slice(0,s.key==='ayurveda'?4:3).map(x=><Link key={x} to={`/services/${s.key}`}>{x}</Link>)}</div>)}</div>
  </div><NavLink to="/services/nutrition">Diet</NavLink><NavLink to="/services/yoga">Yoga</NavLink><NavLink to="/services/mind-body-wellness">Wellness</NavLink><NavLink to="/articles">Blog</NavLink><NavLink to="/book-consultation">Contact</NavLink>
 </nav><Button to="/book-consultation" tone="green" className="header-cta">Book Consultation</Button><button ref={menuButtonRef} className="menu-toggle" aria-label="Open navigation" aria-expanded={open} onClick={()=>setOpen(true)}><span/><span/></button></div>
 <div ref={drawerRef} className={`drawer ${open?'open':''}`} aria-hidden={!open}><button className="drawer-close" onClick={()=>{setOpen(false);menuButtonRef.current?.focus()}} aria-label="Close navigation">×</button><Logo/><nav aria-label="Mobile navigation"><NavLink to="/">Home</NavLink><NavLink to="/about">About</NavLink><button aria-expanded={servicesOpen} onClick={()=>setServicesOpen(v=>!v)}>Services <span>{servicesOpen?'−':'+'}</span></button>{servicesOpen&&<div className="mobile-services">{services.map(s=><Link key={s.key} to={`/services/${s.key}`}>{s.title}</Link>)}</div>}<NavLink to="/programs">Programs</NavLink><NavLink to="/ayurveda">Ayurveda</NavLink><NavLink to="/articles">Articles</NavLink></nav><Button to="/book-consultation">Book a Consultation</Button></div>{open&&<button className="drawer-scrim" onClick={()=>setOpen(false)} aria-label="Close menu"/>}
 </header>
}

function Eyebrow({children}){return <div className="eyebrow"><span/><>{children}</></div>}
function OrganicDivider({tone='cream'}){return <div className={`organic-divider ${tone}`} aria-hidden="true"><svg viewBox="0 0 1440 90" preserveAspectRatio="none"><path d="M0 20C190 92 390 32 610 52c248 23 470 40 830-8v46H0Z"/></svg></div>}

function Hero(){return <section className="hero"><div className="hero-copy"><div className="hero-botanical" aria-hidden="true"><HeroFoliage/></div><div className="hero-inner"><Eyebrow>Holistic healing for a brighter you</Eyebrow><h1><span>Ancient</span><span>Wisdom.</span><span>Modern</span><span>Wellbeing.</span></h1><p>Personalized Ayurveda, Nutrition, Yoga &amp; Wellness for a healthier, happier life.</p><Button to="/book-consultation">Book a Consultation</Button><div className="trust-row">{['Natural Healing','Personalized Care','Holistic Wellbeing'].map(x=><div key={x}><Leaf/><span>{x}</span></div>)}</div></div></div><div className="hero-visual-shell"><svg className="hero-gold-arc" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M7 0C-7 28-8 71 17 100"/></svg><div className="hero-image-mask"><picture><source media="(max-width:700px)" srcSet="/images/ayurveda/hero-ayurveda-mobile.webp"/><img src="/images/ayurveda/hero-ayurveda-desktop.webp" alt="Stone mortar, herbs and traditional Ayurvedic vessels in a botanical setting" fetchPriority="high"/></picture><blockquote>“Balance<br/>Heals<br/>Everything”<span className="quote-rule"/><Leaf/></blockquote><div className="hero-panel"><div><span>Good Health</span><p>A natural way of life</p></div></div></div></div><img className="hero-transition-branch" src="/images/ayurveda/botanical-branch-hero.png" alt="" aria-hidden="true"/><OrganicDivider/></section>}

function Philosophy(){return <section className="section philosophy"><img className="philosophy-branch" src="/images/ayurveda/botanical-branch-hero.webp" alt="" aria-hidden="true"/><div className="container philosophy-grid"><Reveal><Eyebrow>Our philosophy</Eyebrow><h2>Rooted in Tradition.<br/>Designed for Today.</h2><p>At AyurvedaVaidya.com, we bring the timeless wisdom of Ayurveda into modern life. Our approach blends authentic knowledge, personalized guidance and compassionate care to help you achieve lasting wellbeing—naturally.</p><Button to="/about" tone="gold">Our Story</Button></Reveal><Reveal className="philosophy-art" delay={100}><SageArt/><blockquote><b>“</b>True wellness is a balance of body, mind and spirit.<Leaf/></blockquote></Reveal><Reveal className="principles" delay={180}>{['Authentic Knowledge','Modern Application','Personalized Care','A Healthier Tomorrow'].map(x=><div key={x}><span className="principle-dot"><Leaf/></span><span>{x}</span></div>)}</Reveal></div></section>}

function Pillars(){return <section className="section pillars"><div className="botanical-outline" aria-hidden="true"/><div className="container"><Reveal className="section-heading centered"><Eyebrow>A complete approach</Eyebrow><h2>Our Wellness Pillars</h2><p>One personalized plan. Four dimensions of wellbeing.</p></Reveal><div className="pillar-grid">{services.map((s,i)=><Reveal key={s.key} delay={i*70}><Link className="pillar-card" to={`/services/${s.key}`}><div className="card-image"><img src={s.image} alt="" loading="lazy"/></div><div className="pillar-body"><Leaf/><h3>{s.title}</h3><p>{s.short}</p><span>Explore <Arrow/></span></div></Link></Reveal>)}</div></div><OrganicDivider tone="cream"/></section>}

function WhyChoose(){return <section className="section why"><div className="container why-grid"><Reveal><Eyebrow>Why choose us</Eyebrow><h2>More Than Care.<br/>A Healthier Tomorrow.</h2><p>We combine authentic Ayurvedic wisdom with modern scientific understanding to create personalized solutions for your unique journey.</p><Button to="/services">Our Approach</Button></Reveal><div className="benefit-grid">{['Personalized Treatment Plans','Natural & Safe Therapies','Experienced Vaidyas & Experts','Holistic Mind–Body Approach'].map((x,i)=><Reveal delay={i*70} key={x}><div className="benefit"><Leaf/><span>{x}</span></div></Reveal>)}</div><Reveal className="landscape-wrap"><div className="landscape"><img src="/images/ayurveda/why-choose-us.webp" alt="Serene green foothills at sunrise" loading="lazy"/><div>Healthy people<br/>Happier world<Leaf/></div></div></Reveal></div></section>}

function Programs(){return <section className="section programs"><div className="container"><Reveal className="heading-row"><div><Eyebrow>Our programs</Eyebrow><h2>Healing Journeys for Every Need</h2><p>Explore focused wellness programs designed around different health and lifestyle goals.</p></div><Button to="/programs">View All Programs</Button></Reveal><div className="program-grid">{programs.map((p,i)=><Reveal delay={i*70} key={p.title}><Link className="program-card" to="/programs"><img src={p.image} alt="" loading="lazy"/><div><h3>{p.title}</h3><p>{p.text}</p><span>Learn More <Arrow/></span></div></Link></Reveal>)}</div></div></section>}

function Experts(){return <section className="experts"><div className="experts-leaf" aria-hidden="true"/><div className="container expert-grid"><Reveal className="expert-quote"><blockquote>“Healing begins<br/>with listening.”</blockquote><span>— Our care philosophy</span></Reveal><Reveal className="expert-portrait"><img src="/images/ayurveda/expert-placeholder.webp" alt="Placeholder portrait representing an Ayurveda and wellness clinician" loading="lazy"/><span>Development placeholder — replace with actual clinician photography</span></Reveal><Reveal className="expert-copy"><Eyebrow>Meet our experts</Eyebrow><h2>Guided by Experience.<br/>Driven by Compassion.</h2><p>Our multidisciplinary approach brings Ayurveda, nutrition, yoga and mind–body wellness together to create practical, personalized care for modern life.</p><Button to="/about">Meet Our Team</Button></Reveal><div className="trust-statements">{['Personalized Approach','Integrated Wellness','Continuity of Care'].map(x=><div key={x}><Leaf/><span>{x}</span></div>)}</div></div><OrganicDivider tone="cream"/></section>}

function Testimonials(){const [page,setPage]=useState(0);const cards=['Verified patient testimonial will appear here.','Verified patient testimonial will appear here.','Verified patient testimonial will appear here.'];return <section className="section testimonials"><div className="container"><Reveal className="testimonial-head"><div><Eyebrow>Real stories. Real wellbeing.</Eyebrow><h2>What Our Patients Say</h2></div><div className="carousel-controls"><button onClick={()=>setPage((page+2)%3)} aria-label="Previous testimonial">←</button><button onClick={()=>setPage((page+1)%3)} aria-label="Next testimonial">→</button></div></Reveal><div className="testimonial-grid">{cards.map((x,i)=>{const n=(i+page)%3;return <article className="testimonial-card" key={i}><Leaf/><p>“{cards[n]}”</p><div><strong>Verified Patient</strong><span>Placeholder content</span></div></article>})}</div></div></section>}

function Articles(){return <section className="section articles"><div className="container"><Reveal className="heading-row"><div><Eyebrow>Insights for a healthier you</Eyebrow><h2>From Our Journal</h2><p>Explore expert-led educational content on Ayurveda and integrated wellbeing.</p></div><Button to="/articles">View All Articles</Button></Reveal><div className="article-grid">{articles.map((a,i)=><Reveal delay={i*70} key={a.title}><Link className="article-card" to="/articles"><img src={a.image} alt="" loading="lazy"/><div><span className="category">{a.category}</span><h3>{a.title}</h3><span className="read">Read Article <Arrow/></span></div></Link></Reveal>)}</div></div></section>}

function ConsultationCTA(){return <section className="consult-cta"><div className="container cta-grid"><Reveal><Eyebrow>Take the first step today</Eyebrow><h2>Your Journey to Better<br/>Wellbeing Begins Here.</h2></Reveal><Reveal delay={100}><p>Book a consultation and let our team understand your needs and guide you toward an appropriate personalized wellness plan.</p><Button to="/book-consultation">Book a Consultation</Button></Reveal></div><img src="/images/ayurveda/cta-ayurveda.webp" alt="" aria-hidden="true" loading="lazy"/></section>}

function Footer(){return <footer className="site-footer"><div className="container footer-grid"><div><Logo footer/><p>Ancient Wisdom. Modern Wellbeing.</p></div><div><h3>Quick Links</h3>{[['Home','/'],['About','/about'],['Services','/services'],['Programs','/programs'],['Ayurveda','/ayurveda'],['Articles','/articles'],['Contact','/book-consultation']].map(([x,to])=><Link key={x} to={to}>{x}</Link>)}</div><div><h3>Our Services</h3>{services.map(s=><Link key={s.key} to={`/services/${s.key}`}>{s.title}</Link>)}<Link to="/book-consultation">Consultations</Link></div><div className="newsletter"><h3>Stay Connected</h3><p>Join our newsletter for wellness insights and updates.</p><form onSubmit={e=>e.preventDefault()}><label className="sr-only" htmlFor="newsletter-email">Email address</label><input id="newsletter-email" type="email" placeholder="Your email address" required/><button aria-label="Subscribe">→</button></form><small>Newsletter integration required before launch.</small></div></div><div className="footer-bottom container"><span>© {new Date().getFullYear()} AyurvedaVaidya.com. All rights reserved.</span><div className="legal"><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms</Link><Link to="/disclaimer">Wellness Disclaimer</Link></div><span className="live"><Leaf/>Live Naturally. Live Fully.</span></div><div className="disclaimer container">Information on this website is intended for general educational and wellness purposes and is not a substitute for individualized medical advice, diagnosis or emergency care. Final wording should be reviewed by a qualified professional.</div></footer>}

function Home(){return <main><Hero/><Philosophy/><Pillars/><WhyChoose/><Programs/><Experts/><Testimonials/><Articles/><ConsultationCTA/></main>}

const pageCopy={
 about:{eyebrow:'Our philosophy',title:'Rooted in tradition. Designed for modern life.',intro:'AyurvedaVaidya brings Ayurveda, nutrition, yoga and mind–body wellness into one thoughtful, personalized approach.',body:'Our work begins by listening. We consider individual constitution, routines, food, movement, rest and the realities of everyday life before suggesting an appropriate wellness path.'},
 programs:{eyebrow:'Focused wellness journeys',title:'Programs designed around real life.',intro:'Explore supportive, personalized programs spanning rejuvenation, metabolic wellbeing, stress and sleep, and seasonal wellness.',body:'Each program is designed to complement appropriate medical care where needed. Recommendations are tailored after consultation rather than prescribed through a generic online checklist.'},
 ayurveda:{eyebrow:'Ayurveda, thoughtfully applied',title:'Ancient perspective. Practical guidance.',intro:'Discover personalized Ayurvedic wellness guidance grounded in individual constitution, daily rhythms and seasonal context.',body:'Our approach translates traditional principles into clear, practical routines for contemporary life while avoiding one-size-fits-all claims.'},
 articles:{eyebrow:'The AyurvedaVaidya journal',title:'Ideas for considered wellbeing.',intro:'Educational perspectives on Ayurveda, nutrition, yoga and the mind–body relationship.',body:'Articles are prepared for general education and should not replace individualized health advice.'}
}

function EditorialPage({type}){const c=pageCopy[type];return <main><section className="inner-hero"><div className="container"><Eyebrow>{c.eyebrow}</Eyebrow><h1>{c.title}</h1><p>{c.intro}</p></div></section><section className="section inner-content"><div className="container editorial-grid"><div><h2>A more connected view of wellbeing.</h2><p>{c.body}</p><Button to="/book-consultation">Book a Consultation</Button></div><div className="editorial-note"><Leaf/><blockquote>“Small, consistent choices shape the rhythm of wellbeing.”</blockquote></div></div>{type==='programs'&&<div className="container program-grid inner-cards">{programs.map(p=><Link className="program-card" to="/book-consultation" key={p.title}><img src={p.image} alt=""/><div><h3>{p.title}</h3><p>{p.text}</p><span>Enquire <Arrow/></span></div></Link>)}</div>}{type==='articles'&&<div className="container article-grid inner-cards">{articles.map(a=><article className="article-card" key={a.title}><img src={a.image} alt=""/><div><span className="category">{a.category}</span><h3>{a.title}</h3><p>Editorial content placeholder — publication details to be supplied.</p></div></article>)}</div>}</section></main>}

function ServicesPage({single}){const data=single?services.find(s=>s.key===single):null;return <main><section className="inner-hero services-hero"><div className="container"><Eyebrow>{data?data.title:'Ayurveda 360°'}</Eyebrow><h1>{data?data.subtitle:'Four dimensions. One personalized path.'}</h1><p>{data?data.short:'Explore a connected approach bringing Ayurveda, nutrition, yoga and mind–body wellness together.'}</p></div></section><section className="section services-list"><div className="container">{(data?[data]:services).map((s,i)=><article className="service-band" key={s.key}><div className="service-index">0{i+1}</div><div><Eyebrow>{s.title}</Eyebrow><h2>{s.subtitle}</h2><p>{s.short}</p><Button to="/book-consultation">Discuss Your Needs</Button></div><div className="service-items">{s.items.map(x=><div key={x}><Leaf/><span>{x}</span></div>)}</div></article>)}</div></section></main>}

function Booking(){const [status,setStatus]=useState(''); const submit=e=>{e.preventDefault();if(!e.currentTarget.checkValidity()){setStatus('Please complete all required fields.');return}setStatus('Your details are ready. Booking delivery is not connected yet; no appointment has been created.')};return <main><section className="inner-hero booking-hero"><div className="container"><Eyebrow>Begin with a conversation</Eyebrow><h1>Book Your Consultation</h1><p>Tell us how you would like to begin. Please do not include detailed medical history or emergency information in this form.</p></div></section><section className="section booking-section"><div className="container booking-grid"><div><Eyebrow>What to expect</Eyebrow><h2>A thoughtful first step.</h2><p>This form captures only the contact and scheduling details needed for an initial conversation. A secure booking or email service must be connected before launch.</p><div className="form-note"><Leaf/><span>For emergencies, contact your local emergency service. This form is not monitored for urgent care.</span></div></div><form className="booking-form" onSubmit={submit} noValidate><label>Full name<input name="name" required autoComplete="name"/></label><div className="form-row"><label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Phone<input name="phone" type="tel" required autoComplete="tel"/></label></div><div className="form-row"><label>Preferred consultation area<select required defaultValue=""><option value="" disabled>Select an area</option>{services.map(s=><option key={s.key}>{s.title}</option>)}</select></label><label>Consultation mode<select required defaultValue=""><option value="" disabled>Select a mode</option><option>Online</option><option>In person</option><option>Phone</option></select></label></div><div className="form-row"><label>Preferred date<input name="date" type="date" required/></label><label>Preferred time<input name="time" type="time" required/></label></div><label>Optional message<textarea name="message" rows="4" placeholder="A short note about what you would like support with (no detailed medical history)."/></label><label className="consent"><input type="checkbox" required/><span>I agree that AyurvedaVaidya may use these details to respond to my consultation request and I have read the privacy notice.</span></label><button className="btn btn-gold" type="submit">Request Consultation <Arrow/></button><p className="form-status" role="status">{status}</p></form></div></section></main>}

function Legal({type}){const title={privacy:'Privacy Policy',terms:'Terms of Use',disclaimer:'Medical & Wellness Disclaimer'}[type];return <main><section className="inner-hero short"><div className="container"><Eyebrow>Website information</Eyebrow><h1>{title}</h1><p>Draft placeholder page. Final content must be supplied and reviewed before launch.</p></div></section><section className="section legal-page"><div className="container"><h2>Content review required</h2><p>This page is intentionally not populated with fabricated legal terms. Connect the final, professionally reviewed copy before publishing the site.</p>{type==='disclaimer'&&<p>Information on this website is intended for general educational and wellness purposes and is not a substitute for individualized medical advice, diagnosis or emergency care.</p>}</div></section></main>}

function ScrollTop(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});const labels={'/':'Ayurveda, Nutrition, Yoga & Mind-Body Wellness','/about':'About','/services':'Services','/programs':'Wellness Programs','/ayurveda':'Ayurveda','/articles':'Wellness Articles','/book-consultation':'Book a Consultation','/privacy':'Privacy Policy','/terms':'Terms of Use','/disclaimer':'Medical & Wellness Disclaimer'};const service=services.find(s=>pathname===`/services/${s.key}`);document.title=`${service?service.title:labels[pathname]||'AyurvedaVaidya'} | AyurvedaVaidya`},[pathname]);return null}
function App(){return <><ScrollTop/><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<EditorialPage type="about"/>}/><Route path="/programs" element={<EditorialPage type="programs"/>}/><Route path="/ayurveda" element={<EditorialPage type="ayurveda"/>}/><Route path="/articles" element={<EditorialPage type="articles"/>}/><Route path="/services" element={<ServicesPage/>}/>{services.map(s=><Route key={s.key} path={`/services/${s.key}`} element={<ServicesPage single={s.key}/>}/>) }<Route path="/book-consultation" element={<Booking/>}/><Route path="/privacy" element={<Legal type="privacy"/>}/><Route path="/terms" element={<Legal type="terms"/>}/><Route path="/disclaimer" element={<Legal type="disclaimer"/>}/><Route path="*" element={<EditorialPage type="about"/>}/></Routes><Footer/></>}

export default App
